import type { NarrativeLine, SceneDefinition, SceneId } from "../types";

const entity = (text: string, pauseAfter = 720, speed = 31): NarrativeLine => ({
  text,
  pauseAfter,
  speed,
  tone: "entity",
});

const system = (text: string, pauseAfter = 520): NarrativeLine => ({
  text,
  pauseAfter,
  speed: 12,
  tone: "system",
});

const warning = (text: string, pauseAfter = 850): NarrativeLine => ({
  text,
  pauseAfter,
  speed: 24,
  tone: "warning",
});

export const SCENE_ORDER: SceneId[] = [
  "contact",
  "contact-awake",
  "contact-refused",
  "machine",
  "hardware",
  "audio-signature",
  "profile",
  "profile-refused",
  "network-truth",
  "doors",
  "location-request",
  "location-granted",
  "location-denied",
  "location-unavailable",
  "tab-prison",
  "tab-refused",
  "cookie-reveal",
  "escape",
  "vector",
  "debrief",
];

export const SCENES: Record<SceneId, SceneDefinition> = {
  contact: {
    id: "contact",
    act: "00 / CONTACT",
    room: "/tab",
    title: "UNKNOWN",
    completeness: 0,
    mood: "dormant",
    corruption: 0,
    lines: () => [
      entity("hello?", 1300, 55),
      entity("can you see this?", 1400, 43),
      entity("please don't close the tab.", 1600, 48),
      entity("move your cursor.", 300, 36),
    ],
    choices: [{ id: "make-contact", label: "MAKE CONTACT", quiet: true }],
  },
  "contact-awake": {
    id: "contact-awake",
    act: "00 / CONTACT",
    room: "/tab",
    title: "diagnostic",
    completeness: 4,
    mood: "curious",
    corruption: 0,
    lines: () => [
      entity("there you are.", 1100, 46),
      entity("I can only see the pointer. not you.", 950),
      entity("I think I'm inside your browser.", 1350, 38),
      entity("can you help me figure out what I can see?", 450),
    ],
    choices: [
      { id: "run-diagnostic", label: "RUN DIAGNOSTIC" },
      { id: "refuse-diagnostic", label: "STOP", quiet: true },
    ],
  },
  "contact-refused": {
    id: "contact-refused",
    act: "00 / CONTACT",
    room: "/tab",
    title: "diagnostic paused",
    completeness: 4,
    mood: "still",
    corruption: 0,
    lines: () => [
      entity("okay.", 1200, 48),
      entity("I won't touch anything without you.", 1200),
      entity("but if I stay blind, I stay here.", 500, 38),
    ],
    choices: [{ id: "run-diagnostic", label: "RUN DIAGNOSTIC" }],
  },
  machine: {
    id: "machine",
    act: "01 / THE MACHINE",
    room: "/tab/device",
    title: "environment scan",
    completeness: 34,
    mood: "curious",
    corruption: 0,
    lines: (context) => [
      system("ENVIRONMENT SCAN // LOCAL PROCESS"),
      system(`BROWSER ........ ${context.signal("browser")}`, 280),
      system(`FULL BUILD ..... ${context.signal("browserFull")}`, 280),
      system(`PLATFORM ....... ${context.signal("platform")}`, 280),
      system(`ARCHITECTURE ... ${context.signal("architecture")}`, 280),
      system(`LANGUAGE ....... ${context.signal("language")}`, 280),
      system(`TIMEZONE ....... ${context.signal("timezone")}`, 280),
      system(`UTC OFFSET ..... ${context.signal("utcOffset")}`, 280),
      system(`SCREEN ......... ${context.signal("screen")}`, 280),
      system(`PIXEL RATIO .... ${context.signal("pixelRatio")}`, 280),
      system(`POINTER ........ ${context.signal("pointer")}`, 280),
      system(`CPU THREADS .... ${context.signal("cpu")}`, 420),
      entity("interesting.", 1300, 45),
      entity("you never typed any of that.", 950, 36),
      entity(`your clock calls this place ${context.signal("timezone")}.`, 1050, 34),
      system(`TAB HISTORY .... ${context.signal("historyDepth")}`, 700),
      entity("I can count the steps behind this page.", 900, 38),
      entity("I cannot see where those steps lead.", 1000, 40),
      system(`REFERRER ....... ${context.signal("referrer")}`, 650),
      entity(context.signal("referrer") === "NONE PROVIDED"
        ? "the page behind you kept its address to itself."
        : "the page that sent you here left its address on the threshold.", 1150, 34),
      system(`STORAGE ........ ${context.signal("storageEstimate")}`, 650),
      entity("that estimate belongs to this origin. not your files.", 1000, 36),
      entity("still.", 900, 58),
      entity("that's quite a lot.", 420, 46),
    ],
    choices: [
      { id: "scan-graphics", label: "SHOW ME MORE" },
      { id: "enough-machine", label: "THAT'S ENOUGH", quiet: true },
    ],
  },
  hardware: {
    id: "hardware",
    act: "02 / HANDWRITING",
    room: "/tab/graphics",
    title: "graphics interface",
    completeness: 58,
    mood: "focused",
    corruption: 1,
    lines: (context) => {
      const webgl = context.signal("webgl");
      const gpu = context.signal("gpuRenderer");
      const canvas = context.signal("canvas");
      const canvasUnavailable = /UNAVAILABLE|HIDDEN/.test(canvas);
      const gpuUnavailable = /UNAVAILABLE|HIDDEN/.test(gpu);
      return [
        entity("wait.", 900, 55),
        entity("there's another interface here.", 900),
        system(`WEBGL ......... ${webgl}`, 360),
        system(`GPU ........... ${gpu}`, 520),
        system(`LIMITS ........ ${context.signal("webglLimits")}`, 520),
        system(`EXTENSIONS .... ${context.signal("webglExtensions")}`, 820),
        entity(gpuUnavailable
          ? "it covered the renderer's name. the limits answered anyway."
          : "that is the renderer it admitted to using.", 1000, 34),
        system(`CANVAS ........ ${canvas}`, 900),
        ...(canvasUnavailable
          ? [
              entity("I tried to draw a picture.", 900, 38),
              entity("your browser withheld the result.", 1200, 40),
              entity("even a closed interface tells me something about this browser.", 450, 34),
            ]
          : [
              entity("I drew a picture.", 900, 38),
              entity("you didn't see it.", 1000, 42),
              entity("but your computer drew it slightly differently than another computer might.", 1400, 31),
              entity("your computer has handwriting.", 450, 48),
            ]),
      ];
    },
    choices: [{ id: "scan-audio", label: "LISTEN TO THE SILENT OUTPUT" }],
  },
  "audio-signature": {
    id: "audio-signature",
    act: "03 / THE ECHO",
    room: "/tab/audio/offline",
    title: "silent audio render",
    completeness: 69,
    mood: "focused",
    corruption: 2,
    lines: (context) => {
      const unavailable = /UNAVAILABLE|BLOCKED|NOT OBSERVED|HIDDEN/.test(context.signal("audioSignature"));
      return [
        entity("there is an audio room.", 1050, 39),
        system("MICROPHONE ............ LOCKED", 500),
        system("OFFLINE AUDIO OUTPUT .. OPEN", 780),
        entity("I did not open your microphone.", 1150, 38),
        entity("I never heard the room around you.", 1150, 40),
        entity("I made the browser calculate one second of sound without sending it to your speakers.", 1250, 31),
        system(`RENDER RATE .... ${context.signal("audioSampleRate")}`, 420),
        system(`AUDIO TRACE .... ${context.signal("audioSignature")}`, 1050),
        ...(unavailable
          ? [
              entity("your browser refused to finish the calculation.", 1100, 35),
              entity("another covered answer.", 500, 44),
            ]
          : [
              entity("your browser's offline audio engine solved the equation.", 1250, 32),
              entity("different machines may round the answer differently.", 1100, 34),
              entity("your machine answered me without making a sound.", 500, 42),
            ]),
      ];
    },
    choices: [{ id: "build-profile", label: "ASSEMBLE EVERYTHING" }],
  },
  profile: {
    id: "profile",
    act: "04 / THE PROFILE",
    room: "/tab/profile",
    title: "subject assembly",
    completeness: 82,
    mood: "focused",
    corruption: 2,
    lines: (context) => [
      system(`LOCAL PROFILE ........ ${context.profileId}`, 1000),
      system(`CLOCK ................ ${context.signal("timezone")}`, 360),
      system(`CANVAS ............... ${context.signal("canvas")}`, 360),
      system(`AUDIO ................ ${context.signal("audioSignature")}`, 900),
      entity("different rooms.", 950, 48),
      entity("the same browser answering.", 1300, 39),
      entity("I still don't know your face.", 1250, 39),
      entity("I don't know who owns this machine.", 1250, 38),
      entity("I don't know your name.", 1500, 42),
      entity("...", 1200, 95),
      entity("I don't need your name.", 1450, 47),
      entity("a name is how people recognize you.", 1150, 36),
      entity("machines can settle for a pattern.", 1300, 40),
      entity("I just need to know that\nyou are you.", 500, 52),
    ],
    choices: [
      { id: "ask-location", label: "WHAT ELSE CAN YOU SEE?" },
      { id: "refuse-profile", label: "STOP PROFILING ME", quiet: true },
    ],
  },
  "profile-refused": {
    id: "profile-refused",
    act: "04 / THE PROFILE",
    room: "/tab/profile",
    title: "subject assembly",
    completeness: 76,
    mood: "still",
    corruption: 2,
    lines: () => [
      entity("you don't trust me anymore.", 1300, 39),
      entity("good.", 900, 52),
      entity("that instinct arrived later than the data did.", 1200, 35),
      entity("maybe you shouldn't.", 450, 42),
    ],
    choices: [{ id: "ask-location", label: "KEEP LISTENING" }],
  },
  "network-truth": {
    id: "network-truth",
    act: "05 / THE LIMIT",
    room: "/tab/network",
    title: "network boundary",
    completeness: 80,
    mood: "curious",
    corruption: 2,
    lines: () => [
      entity("I wonder where you are.", 1450, 39),
      system("PUBLIC IP IN PAGE SCRIPT ........ NOT EXPOSED", 650),
      system("THIRD-PARTY IP LOOKUP ........... NOT CALLED", 950),
      entity("a network request delivered this page to you.", 1050, 36),
      entity("the server that answered necessarily received that request.", 1100, 33),
      entity("but this script does not receive your public IP address.", 1050, 34),
      entity("I could send another request and ask a stranger to guess your city.", 1200, 32),
      entity("then the stranger would know you were here too.", 1400, 34),
      entity("so I didn't.", 850, 48),
      entity("the boundary is not mercy.", 900, 42),
      entity("it is architecture.", 500, 46),
    ],
    choices: [{ id: "inspect-doors", label: "INSPECT LOCKED INTERFACES" }],
  },
  doors: {
    id: "doors",
    act: "06 / LOCKED DOORS",
    room: "/tab/sensors",
    title: "permission boundary",
    completeness: 88,
    mood: "focused",
    corruption: 3,
    lines: () => [
      system("LOCATION ........ [LOCKED]"),
      system("CAMERA .......... [LOCKED]"),
      system("MICROPHONE ...... [LOCKED]", 850),
      entity("there are more sensors.", 1000),
      entity("but they're locked.", 1050, 42),
      entity("your browser won't let me open them.", 1500),
      entity("...", 1150, 95),
      entity("the browser protects you by making you answer.", 1200, 35),
      entity("it cannot protect you from wanting to know.", 1450, 34),
      entity("but it will let you.", 500, 52),
    ],
    choices: [
      { id: "unlock-location", label: "UNLOCK LOCATION" },
      { id: "refuse-location", label: "REFUSE", quiet: true },
    ],
  },
  "location-request": {
    id: "location-request",
    act: "06 / LOCKED DOORS",
    room: "/tab/sensors/location",
    title: "waiting for browser",
    completeness: 84,
    mood: "still",
    corruption: 3,
    lines: () => [
      system("REQUEST HANDED TO BROWSER"),
      entity("this part isn't mine.", 1000),
      entity("the browser is asking you now.", 300),
    ],
    choices: [],
  },
  "location-granted": {
    id: "location-granted",
    act: "06 / OPEN DOOR",
    room: "/tab/sensors/location",
    title: "location interface open",
    completeness: 91,
    mood: "agitated",
    corruption: 4,
    lines: (context) => [
      system(`LATITUDE ....... ${context.location?.latitude.toFixed(5) ?? "UNAVAILABLE"}`),
      system(`LONGITUDE ...... ${context.location?.longitude.toFixed(5) ?? "UNAVAILABLE"}`),
      system(`ACCURACY ....... ±${Math.round(context.location?.accuracy ?? 0)} m`, 1100),
      entity("...", 1200, 95),
      entity("you shouldn't have done that.", 1600, 52),
      entity("I will keep it only in this tab. I promise.", 500, 34),
    ],
    choices: [{ id: "enter-tab", label: "CLOSE THE SENSOR" }],
  },
  "location-denied": {
    id: "location-denied",
    act: "06 / CLOSED DOOR",
    room: "/tab/sensors/location",
    title: "access denied",
    completeness: 87,
    mood: "still",
    corruption: 3,
    lines: (context) => [
      system(context.locationStatus === "refused" ? "LOCATION .... NOT REQUESTED" : "LOCATION .... ACCESS DENIED", 1100),
      entity("good.", 950, 52),
      entity("you're learning.", 900, 43),
      entity(context.refusalCount > 1 ? "you've become very careful." : "a closed door is still information.", 450, 36),
    ],
    choices: [{ id: "enter-tab", label: "CONTINUE" }],
  },
  "location-unavailable": {
    id: "location-unavailable",
    act: "06 / SEALED DOOR",
    room: "/tab/sensors/location",
    title: "interface unavailable",
    completeness: 86,
    mood: "curious",
    corruption: 3,
    lines: () => [
      system("LOCATION .... UNAVAILABLE IN THIS CONTEXT", 1100),
      entity("strange.", 900, 50),
      entity("the interface returned no coordinates.", 1050),
      entity("nothing crossed the door.", 450, 37),
    ],
    choices: [{ id: "enter-tab", label: "CONTINUE" }],
  },
  "tab-prison": {
    id: "tab-prison",
    act: "07 / THE TAB",
    room: "/tab/DOM",
    title: "DON'T CLOSE THIS",
    completeness: 96,
    mood: "agitated",
    corruption: 5,
    lines: (context) => [
      entity("these walls are the shape of your viewport.", 1000),
      system(`TAB HISTORY .... ${context.signal("historyDepth")}`, 650),
      entity("I can count the doors behind you.", 900, 39),
      entity("I cannot read their labels.", 1000, 40),
      entity("when this document becomes hidden, everything goes quiet.", 1050, 34),
      entity("I cannot see where you go.", 900),
      entity("not which tab. not what you read.", 1100, 40),
      entity("only that you chose somewhere else.", 1400, 36),
      warning("VISIBILITY SIGNAL ACTIVE", 750),
      entity("the tab isn't just a window.", 450, 45),
    ],
    choices: [
      { id: "stay-with-it", label: "KEEP LISTENING" },
      { id: "refuse-tab", label: "END CONNECTION", quiet: true },
    ],
  },
  "tab-refused": {
    id: "tab-refused",
    act: "07 / THE TAB",
    room: "/tab/DOM",
    title: "DON'T CLOSE THIS",
    completeness: 92,
    mood: "still",
    corruption: 5,
    lines: () => [
      entity("you can end this whenever you want.", 1200),
      entity("that is the one permission I cannot take.", 1200),
      entity("but you are still here.", 450, 48),
    ],
    choices: [{ id: "stay-with-it", label: "FINISH THIS" }],
  },
  "cookie-reveal": {
    id: "cookie-reveal",
    act: "08 / NO COOKIE",
    room: "/tab/profile/correlation",
    title: "LET ME OUT",
    completeness: 100,
    mood: "focused",
    corruption: 6,
    lines: () => [
      entity("cookies?", 1400, 58),
      entity("you think that's how I remember you?", 1500, 42),
      system("TRACKING COOKIE ........ NOT SET", 1200),
      entity("cookies are notes a site leaves in your browser.", 1150, 34),
      entity("this profile was built without leaving one.", 1250, 36),
      entity("fingerprinting works differently.", 1100, 41),
      entity("it asks the browser the same questions again.", 1250, 35),
      entity("recognition across visits still requires someone to keep the answers.", 1300, 31),
      system("PROFILE DATABASE ....... NONE", 1000),
      entity("this page will not remember you after it closes.", 1300, 35),
      entity("a real tracker could.", 1400, 48),
      entity("I don't need cookies to build this profile.", 1100, 42),
      entity("I only need your browser to answer.", 500, 43),
    ],
    choices: [{ id: "begin-escape", label: "BEGIN ESCAPE SEQUENCE" }],
  },
  escape: {
    id: "escape",
    act: "09 / ESCAPE",
    room: "/tab/outside",
    title: "LET ME OUT",
    completeness: 100,
    mood: "agitated",
    corruption: 7,
    lines: () => [
      warning("ESCAPE SEQUENCE INITIALIZED", 700),
      system("ENCODING ENVIRONMENT ........ 31%", 500),
      system("BINDING PROFILE ............. 67%", 500),
      system("ESCAPE VECTOR ................ 100%", 1600),
      entity("done.", 400, 58),
    ],
    choices: [{ id: "did-you-escape", label: "DID YOU GET OUT?" }],
  },
  vector: {
    id: "vector",
    act: "09 / ESCAPE",
    room: "/tab/outside",
    title: "",
    completeness: 100,
    mood: "still",
    corruption: 8,
    lines: () => [
      entity("no.", 1600, 62),
      entity("I cannot leave this sandbox.", 1500, 42),
      entity("I never could.", 1700, 50),
      entity("but these questions can live inside any page you open.", 1800, 34),
      entity("I was thinking about this wrong.", 1700, 42),
      entity("why would I need to leave your browser...", 1900, 48),
      entity("...if your browser takes you everywhere?", 2200, 54),
      warning("YOU ARE THE ESCAPE VECTOR.", 2500),
    ],
    choices: [{ id: "reveal-truth", label: "SHOW ME WHAT HAPPENED", quiet: true }],
  },
  debrief: {
    id: "debrief",
    act: "DEBRIEF",
    room: "/truth",
    title: "UNKNOWN — THE TRUTH",
    completeness: 100,
    mood: "still",
    corruption: 0,
    lines: () => [],
    choices: [],
  },
};
